
services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: data_diff
      ports:
        - 5432:5432
      volumes:
        - ./volumns/postgres:/var/lib/postgresql/data

volumes:
  postgres_data: